version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS

    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1000m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Fetch Streams P2 Environment from CircleCI artifacts
          command: |
            NAVAJO_URL="https://circleci.com/api/v1.1/project/github/Dexels/navajo?circle-token=${CIRCLE_TOKEN}&limit=100&offset=0&filter=successful"
            NAVAJO_VERSION=$(curl -s "$NAVAJO_URL" | jq "[.[]| select(.branch == \"${CIRCLE_BRANCH}\")][0].build_num")
            curl -L -s "https://${NAVAJO_VERSION}-4423334-gh.circle-artifacts.com/0/streams_p2.zip?circle-token=$CIRCLE_TOKEN" -o streams_p2.zip
            unzip -o streams_p2.zip
            rm -rf artifacts.* content.* features* *.index
            rm streams_p2.zip

      # See https://circleci.com/docs/2.0/building-docker-images/
      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Log in with docker registries
          command: |
            docker --version
            echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin

      - run:
          name: Build and push Docker image
          command: |
            SUFFIX=$([[ $CIRCLE_BRANCH = "master" ]] && echo "" || echo "-$CIRCLE_BRANCH")
            PREFIX="3.3"

            DEXELSBASE_IMAGE="dexels/dexels-base"
            DEXELSBASE_URL="https://circleci.com/api/v1.1/project/github/Dexels/dexels-base?circle-token=${CIRCLE_TOKEN}&limit=100&offset=0&filter=successful"
            DEXELSBASE_BUILD=$(curl -s "$DEXELSBASE_URL" | jq "[.[]| select(.branch == \"${CIRCLE_BRANCH}\" and .workflows.job_name == \"package\")][0].build_num")
            DEXELSBASE_VERSION="${PREFIX}.${DEXELSBASE_BUILD}${SUFFIX}"

            TARGET_IMAGE="dexels/navajo-streams"
            TARGET_VERSION="${PREFIX}.${CIRCLE_BUILD_NUM}${SUFFIX}"

            echo "Building '${TARGET_IMAGE}:${TARGET_VERSION}' from '${DEXELSBASE_IMAGE}:${DEXELSBASE_VERSION}'"
            cd ~/repo
            ls -l
            docker  build  --build-arg TAG=${DEXELSBASE_VERSION}  -t "${TARGET_IMAGE}:${TARGET_VERSION}"  .
            docker  push   "${TARGET_IMAGE}:${TARGET_VERSION}"
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
                docker  tag   "${TARGET_IMAGE}:${TARGET_VERSION}" "${TARGET_IMAGE}:latest"
                docker  push  "${TARGET_IMAGE}:latest"
            fi

      - run:
          name: Trigger sportlink.replication build
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
                curl -X POST \
                    --header "Content-Type: application/json" \
                    --header "Circle-Token: ${CIRCLE_TOKEN}" \
                    -d "{ \"branch\" : \"${CIRCLE_BRANCH}\" }" \
                    "https://circleci.com/api/v1.1/project/github/dexels/sportlink.replication/build"
            fi

workflows:
  version: 2
  main:
    jobs:
      - build:
          context:
          - dexels_docker_hub
          filters:
            branches:
              only:
                - master
                - test

